using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// Creates an invisible, continuous collision boundary along the dense forest
/// from practice zone 3 to the temple. The playable clearings and road remain
/// open, while the tree-covered area outside the route cannot be entered.
/// </summary>
public static class ForestBoundaryCollisionBootstrap
{
    private const string BoundaryRootName = "Forest Boundary Collision - Zone 3+";
    private const string RouteWallsName = "Continuous Forest Edge Walls";
    private const string TerrainTreeBlockersName = "Expanded Terrain Tree Blockers";
    private const string SceneTreeBlockersName = "Expanded Scene Tree Blockers";
    private const string PassageAwareMarkerName = "Passage Openings - 길1 길2 길3 길4 - Wide Corridors";
    private const float WallThickness = 3f;
    private const float WallHeight = 50f;
    private const float MinimumTreeRadius = 3f;
    private const float ExtraTrunkRadius = 2.25f;
    private const float PassagePadding = 4f;
    private const float PassageCorridorHalfWidth = 8f;
    private const float PassageCorridorStep = 2f;
    private const float SplitWallLength = 2f;

    private readonly struct RouteBoundaryNode
    {
        public RouteBoundaryNode(float x, float y, float z, float halfWidth)
        {
            Center = new Vector3(x, y, z);
            HalfWidth = halfWidth;
        }

        public Vector3 Center { get; }
        public float HalfWidth { get; }
    }

    // Width expands around combat pads and the temple courtyard, then narrows
    // along connecting trails. Values follow the current graybox route.
    private static readonly RouteBoundaryNode[] BoundaryNodes =
    {
        new RouteBoundaryNode(-2f, 16f,   0f, 13f),
        new RouteBoundaryNode(-12f, 20f, 35f, 35f),
        new RouteBoundaryNode(-7f, 23f,  69f, 13f),
        new RouteBoundaryNode( 5f, 27f, 105f, 12f),
        new RouteBoundaryNode(15f, 30f, 132f, 28f),
        new RouteBoundaryNode(11f, 30f, 159f, 13f),
        new RouteBoundaryNode( 5f, 30f, 187f, 40f),
    };

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    private static void Initialize()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
        SceneManager.sceneLoaded += OnSceneLoaded;
        TryCreateBoundary();
    }

    private static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        TryCreateBoundary();
    }

    private static void TryCreateBoundary()
    {
        // Do not add the level boundary to unrelated scenes.
        if (GameObject.Find("GAIA NATURE - Joseon Temperate Mountain") == null &&
            GameObject.Find("Gaia Terrain_0_0 - FirstVillageTemple") == null)
        {
            return;
        }

        int wallLayer = LayerMask.NameToLayer("Wall");
        if (wallLayer < 0)
            wallLayer = 0;

        GameObject root = GameObject.Find(BoundaryRootName);
        if (root != null && root.transform.Find(PassageAwareMarkerName) == null)
        {
            // Replace a boundary generated by the older version that did not know
            // about the designer-authored 길1~길4 passage markers.
            Object.DestroyImmediate(root);
            root = null;
        }
        else if (root != null)
        {
            return;
        }

        if (root == null)
            root = new GameObject(BoundaryRootName);
        root.layer = wallLayer;

        GameObject environmentFolder = GameObject.Find("90_ENVIRONMENT - Terrain & Nature");
        if (environmentFolder != null && root.transform.parent != environmentFolder.transform)
            root.transform.SetParent(environmentFolder.transform, true);

        List<Bounds> passageBounds = FindPassageBounds(out int passageMarkerCount, out int corridorCellCount);
        var passageMarker = new GameObject(PassageAwareMarkerName);
        passageMarker.transform.SetParent(root.transform, false);
        var passageCount = new GameObject($"Detected Passage Cubes ({passageMarkerCount})");
        passageCount.transform.SetParent(passageMarker.transform, false);
        var corridorCount = new GameObject($"Continuous Passage Cells ({corridorCellCount})");
        corridorCount.transform.SetParent(passageMarker.transform, false);

        if (root.transform.Find(RouteWallsName) == null)
            CreateRouteWalls(root.transform, wallLayer, passageBounds);
        if (root.transform.Find(TerrainTreeBlockersName) == null)
            CreateTerrainTreeBlockers(root.transform, wallLayer, passageBounds);
        if (root.transform.Find(SceneTreeBlockersName) == null)
            CreateSceneTreeBlockers(root.transform, wallLayer, passageBounds);

        Physics.SyncTransforms();
    }

    private static void CreateRouteWalls(Transform root, int wallLayer, List<Bounds> passageBounds)
    {
        var routeWalls = new GameObject(RouteWallsName);
        routeWalls.layer = wallLayer;
        routeWalls.transform.SetParent(root, false);

        Vector3[] leftEdge = new Vector3[BoundaryNodes.Length];
        Vector3[] rightEdge = new Vector3[BoundaryNodes.Length];
        for (int index = 0; index < BoundaryNodes.Length; index++)
        {
            Vector3 tangent;
            if (index == 0)
                tangent = BoundaryNodes[1].Center - BoundaryNodes[0].Center;
            else if (index == BoundaryNodes.Length - 1)
                tangent = BoundaryNodes[index].Center - BoundaryNodes[index - 1].Center;
            else
                tangent = BoundaryNodes[index + 1].Center - BoundaryNodes[index - 1].Center;

            tangent.y = 0f;
            tangent.Normalize();
            Vector3 normal = new Vector3(-tangent.z, 0f, tangent.x);
            leftEdge[index] = BoundaryNodes[index].Center + normal * BoundaryNodes[index].HalfWidth;
            rightEdge[index] = BoundaryNodes[index].Center - normal * BoundaryNodes[index].HalfWidth;
        }

        for (int index = 0; index < BoundaryNodes.Length - 1; index++)
        {
            CreateWallSegmentsWithPassages(routeWalls.transform, $"Forest Wall L {index + 1:00}", leftEdge[index], leftEdge[index + 1], wallLayer, passageBounds);
            CreateWallSegmentsWithPassages(routeWalls.transform, $"Forest Wall R {index + 1:00}", rightEdge[index], rightEdge[index + 1], wallLayer, passageBounds);
        }
    }

    private static void CreateTerrainTreeBlockers(Transform root, int wallLayer, List<Bounds> passageBounds)
    {
        var holder = new GameObject(TerrainTreeBlockersName);
        holder.layer = wallLayer;
        holder.transform.SetParent(root, false);

        int count = 0;
        foreach (Terrain terrain in Terrain.activeTerrains)
        {
            TerrainData data = terrain.terrainData;
            if (data == null || data.treeInstanceCount == 0)
                continue;

            TreePrototype[] prototypes = data.treePrototypes;
            foreach (TreeInstance instance in data.treeInstances)
            {
                float trunkRadius = 0.5f;
                float trunkHeight = 10f;
                if (instance.prototypeIndex >= 0 && instance.prototypeIndex < prototypes.Length)
                {
                    GameObject prefab = prototypes[instance.prototypeIndex].prefab;
                    CapsuleCollider sourceCollider = prefab != null
                        ? prefab.GetComponentInChildren<CapsuleCollider>(true)
                        : null;
                    if (sourceCollider != null)
                    {
                        trunkRadius = sourceCollider.radius;
                        trunkHeight = sourceCollider.height;
                    }
                }

                float worldX = terrain.transform.position.x + instance.position.x * data.size.x;
                float worldZ = terrain.transform.position.z + instance.position.z * data.size.z;
                float groundY = terrain.SampleHeight(new Vector3(worldX, 0f, worldZ)) + terrain.transform.position.y;
                if (IsInsideAnyPassage(new Vector3(worldX, groundY, worldZ), passageBounds))
                    continue;

                float radius = Mathf.Max(MinimumTreeRadius, trunkRadius * instance.widthScale + ExtraTrunkRadius);
                float height = Mathf.Max(10f, trunkHeight * instance.heightScale);

                CapsuleCollider blocker = holder.AddComponent<CapsuleCollider>();
                blocker.isTrigger = false;
                blocker.direction = 1;
                blocker.radius = radius;
                blocker.height = Mathf.Max(height, radius * 2f);
                blocker.center = new Vector3(worldX, groundY + blocker.height * 0.5f, worldZ);
                count++;
            }
        }

        Debug.Log($"Forest collision: created {count} expanded Terrain Tree blockers.");
    }

    private static void CreateSceneTreeBlockers(Transform root, int wallLayer, List<Bounds> passageBounds)
    {
        var holder = new GameObject(SceneTreeBlockersName);
        holder.layer = wallLayer;
        holder.transform.SetParent(root, false);

        int count = 0;
        LODGroup[] lodGroups = Object.FindObjectsByType<LODGroup>(FindObjectsInactive.Exclude, FindObjectsSortMode.None);
        foreach (LODGroup lodGroup in lodGroups)
        {
            if (!LooksLikeTree(lodGroup.name))
                continue;

            CapsuleCollider sourceCollider = lodGroup.GetComponentInChildren<CapsuleCollider>(true);
            float radius = sourceCollider != null
                ? Mathf.Max(MinimumTreeRadius, sourceCollider.radius * MaxHorizontalScale(sourceCollider.transform) + ExtraTrunkRadius)
                : MinimumTreeRadius;
            float height = sourceCollider != null
                ? Mathf.Max(10f, sourceCollider.height * sourceCollider.transform.lossyScale.y)
                : 12f;

            Vector3 groundPosition = lodGroup.transform.position;
            if (IsInsideAnyPassage(groundPosition, passageBounds))
                continue;

            CapsuleCollider blocker = holder.AddComponent<CapsuleCollider>();
            blocker.isTrigger = false;
            blocker.direction = 1;
            blocker.radius = radius;
            blocker.height = Mathf.Max(height, radius * 2f);
            blocker.center = new Vector3(groundPosition.x, groundPosition.y + blocker.height * 0.5f, groundPosition.z);
            count++;
        }

        Debug.Log($"Forest collision: created {count} expanded scene-tree blockers.");
    }

    private static bool LooksLikeTree(string objectName)
    {
        string lower = objectName.ToLowerInvariant();
        return lower.Contains("tree") || lower.Contains("spruce") || lower.Contains("pine") ||
               lower.Contains("oak") || lower.Contains("birch");
    }

    private static float MaxHorizontalScale(Transform target)
    {
        Vector3 scale = target.lossyScale;
        return Mathf.Max(Mathf.Abs(scale.x), Mathf.Abs(scale.z));
    }

    private static List<Bounds> FindPassageBounds(out int markerCount, out int corridorCellCount)
    {
        var passages = new List<Bounds>();
        var markerBounds = new Dictionary<int, Bounds>();
        Transform[] transforms = Object.FindObjectsByType<Transform>(FindObjectsInactive.Include, FindObjectsSortMode.None);
        foreach (Transform target in transforms)
        {
            int markerIndex = GetPassageMarkerIndex(target.name);
            if (markerIndex == 0)
                continue;

            Bounds bounds;
            Collider[] markerColliders = target.GetComponentsInChildren<Collider>(true);
            Renderer[] markerRenderers = target.GetComponentsInChildren<Renderer>(true);
            if (markerColliders.Length > 0)
            {
                bounds = markerColliders[0].bounds;
                for (int index = 1; index < markerColliders.Length; index++)
                    bounds.Encapsulate(markerColliders[index].bounds);
            }
            else if (markerRenderers.Length > 0)
            {
                bounds = markerRenderers[0].bounds;
                for (int index = 1; index < markerRenderers.Length; index++)
                    bounds.Encapsulate(markerRenderers[index].bounds);
            }
            else
            {
                Vector3 size = target.lossyScale;
                size.x = Mathf.Max(Mathf.Abs(size.x), 4f);
                size.y = Mathf.Max(Mathf.Abs(size.y), 4f);
                size.z = Mathf.Max(Mathf.Abs(size.z), 4f);
                bounds = new Bounds(target.position, size);
            }

            if (markerBounds.TryGetValue(markerIndex, out Bounds existingBounds))
            {
                existingBounds.Encapsulate(bounds);
                markerBounds[markerIndex] = existingBounds;
            }
            else
            {
                markerBounds.Add(markerIndex, bounds);
            }
        }

        foreach (KeyValuePair<int, Bounds> marker in markerBounds)
        {
            Bounds expanded = marker.Value;
            expanded.Expand(new Vector3(PassagePadding * 2f, WallHeight * 2f, PassagePadding * 2f));
            passages.Add(expanded);
        }

        corridorCellCount = 0;
        var orderedMarkers = new List<int>(markerBounds.Keys);
        orderedMarkers.Sort();
        for (int index = 0; index < orderedMarkers.Count - 1; index++)
        {
            Bounds from = markerBounds[orderedMarkers[index]];
            Bounds to = markerBounds[orderedMarkers[index + 1]];
            corridorCellCount += AddPassageCorridor(passages, from.center, to.center);
        }

        markerCount = markerBounds.Count;
        Debug.Log($"Forest collision: detected {markerCount} passage cubes and created {corridorCellCount} wide corridor cells.");
        return passages;
    }

    private static int GetPassageMarkerIndex(string objectName)
    {
        string normalized = objectName.Replace(" ", string.Empty);
        if (normalized.StartsWith("길1")) return 1;
        if (normalized.StartsWith("길2")) return 2;
        if (normalized.StartsWith("길3")) return 3;
        if (normalized.StartsWith("길4")) return 4;
        return 0;
    }

    private static int AddPassageCorridor(List<Bounds> passages, Vector3 start, Vector3 end)
    {
        float distance = Vector2.Distance(new Vector2(start.x, start.z), new Vector2(end.x, end.z));
        int steps = Mathf.Max(1, Mathf.CeilToInt(distance / PassageCorridorStep));
        for (int index = 0; index <= steps; index++)
        {
            Vector3 center = Vector3.Lerp(start, end, index / (float)steps);
            passages.Add(new Bounds(
                center,
                new Vector3(PassageCorridorHalfWidth * 2f, WallHeight * 2f, PassageCorridorHalfWidth * 2f)));
        }
        return steps + 1;
    }

    private static bool IsInsideAnyPassage(Vector3 point, List<Bounds> passages, float extraPadding = 0f)
    {
        foreach (Bounds passage in passages)
        {
            if (Mathf.Abs(point.x - passage.center.x) <= passage.extents.x + extraPadding &&
                Mathf.Abs(point.z - passage.center.z) <= passage.extents.z + extraPadding)
            {
                return true;
            }
        }
        return false;
    }

    private static void CreateWallSegmentsWithPassages(
        Transform parent,
        string name,
        Vector3 start,
        Vector3 end,
        int wallLayer,
        List<Bounds> passageBounds)
    {
        float length = Vector2.Distance(new Vector2(start.x, start.z), new Vector2(end.x, end.z));
        int segmentCount = Mathf.Max(1, Mathf.CeilToInt(length / SplitWallLength));
        for (int index = 0; index < segmentCount; index++)
        {
            Vector3 pieceStart = Vector3.Lerp(start, end, index / (float)segmentCount);
            Vector3 pieceEnd = Vector3.Lerp(start, end, (index + 1f) / segmentCount);
            Vector3 midpoint = (pieceStart + pieceEnd) * 0.5f;
            if (IsInsideAnyPassage(midpoint, passageBounds, SplitWallLength))
                continue;

            CreateWallSegment(parent, $"{name}-{index + 1:000}", pieceStart, pieceEnd, wallLayer);
        }
    }

    private static void CreateWallSegment(Transform parent, string name, Vector3 start, Vector3 end, int wallLayer)
    {
        Vector3 flatDirection = end - start;
        flatDirection.y = 0f;
        float length = flatDirection.magnitude;
        if (length < 0.01f)
            return;

        var wall = new GameObject(name);
        wall.layer = wallLayer;
        wall.transform.SetParent(parent, false);
        wall.transform.position = new Vector3(
            (start.x + end.x) * 0.5f,
            (start.y + end.y) * 0.5f + WallHeight * 0.35f,
            (start.z + end.z) * 0.5f);
        wall.transform.rotation = Quaternion.LookRotation(flatDirection.normalized, Vector3.up);

        BoxCollider collider = wall.AddComponent<BoxCollider>();
        collider.isTrigger = false;
        collider.center = Vector3.zero;
        // Small overlap closes seams without bridging across a designed passage gap.
        collider.size = new Vector3(WallThickness, WallHeight, length + 0.3f);
    }
}
